name: Flutter CI

on:
  push:
    branches: [ "feat/core-features-and-offline-db" ]
  pull_request:
    branches: [ "feat/core-features-and-offline-db" ]

jobs:
  build_android_web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build Android APK
        run: flutter build apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Build web
        run: flutter build web
      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Generate platform-specific files
        run: flutter create .
      - name: Restore potentially overwritten files
        run: git restore pubspec.yaml README.md || true
      - name: Get dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --no-codesign